#
# Copyright (c) 2024 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# CONFIG_SERIAL=n
# CONFIG_UART_CONSOLE=n
# CONFIG_LOG=n

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3  # 0=none, 1=err, 2=warn, 3=info, 4=debug
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG_MODE_DEFERRED=y  # Better performance (default)
